[package]
name = "contract"
version = "0.1.1"
authors = ["Maciej Zielinski <maciej@casperlabs.io>"]
edition = "2018"

[lib]
crate-type = ["cdylib"]
doctest = false
test = false

[dependencies]
casperlabs-contract = { git = "https://github.com/casperlabs/casperlabs", package="casperlabs-contract", rev="61d3a54135278ce84053e77c03a22451ceec9073" }
casperlabs-types = { git = "https://github.com/casperlabs/casperlabs", package="casperlabs-types", rev="61d3a54135278ce84053e77c03a22451ceec9073" }
erc20_logic  = { path = "../logic", package = "erc20-logic", default-features = false }
