[package]
name = "contract"
version = "0.1.0"
authors = ["Maciej Zielinski <maciej@casperlabs.io>"]
edition = "2018"

[dependencies]
contract = { package = "casper-contract", version = "0.6.0" }
types = { package = "casper-types", version = "0.6.0" }
casperlabs_contract_macro = { package = "casperlabs_contract_macro", version = "0.1.0"}

[[bin]]
name = "contract"
path = "src/main.rs"
bench = false
doctest = false
test = false

[features]
default = ["contract/std", "types/std"]
